### PR TITLE
Add a statuspage app

### PR DESCRIPTION
**Pull request by arendjantetteroo**
@mrchrisadams Migrating this from the old admin env to a public page on https://status.thegreenwebfoundation.org so we can make this visible. 

We can extend this later with other statistics.

### CODE REVIEW

**Comment by arendjantetteroo** [comment]
Seems one of the tests is failing, which is not caused by this change.

**Comment by mrchrisadams** [comment]
Hey @arendjantetteroo does this need anything else?

**Comment by arendjantetteroo** [comment]
Some way to deploy this :) 
Currently it's just a copy/paste of whats on the server, but would be nice to keep it tracked in git.

**Comment by mrchrisadams** [comment]
Hey @arendjantetteroo - given that the graphite web app let us make these, you reckon we still need this?

We have dashboards like this, and I think we can make them accessible publicly too. This would mean you don't need to use git to make changes.

👍 ?

https://graphite.thegreenwebfoundation.org/dashboard/Rabbit

**Pull request merged**
